jdk:
  - openjdk11
install: true
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "anastasiiakosiak"
    token:
      secure: "$SONAR_TOKEN"
  script:
    # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
   - mvn clean verify sonar:sonar -Pcoverage