language: java
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2

addons:
        sonarcloud:
          organization: "anastasiiakosiak"
          token:
            secure: "$SONAR_TOKEN" # encrypted value of your token

      script:
        # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AnastasiiaKosiak_internet-shop-project